const actPayment = {
   GET_PAYMENT:"GET_PAYMENT",
   SET_PAYMENT:"SET_PAYMENT",

   POST_PAYMENT:"POST_PAYMENT",
   SUCCESS_PAYMENT:"SUCCESS_PAYMENT",
   FAILED_PAYMENT:"FAILED_PAYMENT",

   GET_TICKET:"GET_TICKET",
   SET_TICKET:"SET_TICKET",
   POST_TICKET:"POST_TICKET"

}
export default actPayment;